-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "backgroundColor" TEXT NOT NULL DEFAULT '#bababa',
ADD COLUMN     "ballColor" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "ballSize" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "ballSpeed" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "ownerId" TEXT,
ADD COLUMN     "paddleColor" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "paddleSize" INTEGER NOT NULL DEFAULT 75,
ADD COLUMN     "paddleSpeed" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "scoreLimit" INTEGER NOT NULL DEFAULT 10;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "elo" INTEGER NOT NULL DEFAULT 1500;
