version: '3.8'

services:

    # Nginx
    server:
        build:
            context: ./web/nginx
            dockerfile: Dockerfile
        env_file: .env
        restart: always
        tty: true
        depends_on:
            - web
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./web/app/dist:/usr/share/nginx/html
            - ./web/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - 42Pong

    # VueJs - NodeJs
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        env_file: .env
        restart: always
        tty: true
        ports:
            - "3000:3000"
        #depends_on:
            #- backend
        volumes:
          - ./web/app:/app
        networks:
            - 42Pong

    # NestJs - NodeJs
#    backend:
#        build:
#            context: ./backend
#            dockerfile: Dockerfile
#        env_file: .env
#        restart: always
#        tty: true
#        depends_on:
#            - database
#        volumes:
#            - ./backend/app:/app
#        networks:
#            - 42Pong
#
#    # PostgresSql - Database
#    database:
#        build:
#            context: ./database
#            dockerfile: Dockerfile
#        env_file: .env
#        restart: always
#        tty: true
#        volumes:
#            - database_data:/var/lib/postgresql/data
#        networks:
#          - 42Pong

# Volumes
volumes:
    web_data:
        driver: local
    database_data:
        driver: local

# Networks
networks:
    42Pong:
        driver: bridge
