name: Feature Request
description: Submit a Feature Request
title: "feat:"
labels: 
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Some test of form for issue
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validation:
      required: false
  -type: textarea
 git l